language: cpp

compiler:
  - gcc
  - clang
  
install:
  - sudo apt-get update
  - sudo apt install qt5-default qtbase5-dev cppcheck

script:
  - cd ./src
  - qmake HexEditor.pro
  - make
  # Cppcheck 
  - cppcheck -q --force --enable=warning,style,performance,portability . 2>cppcheck.log
  - cat cppcheck.log
